config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root to: "controller#action"
  # A visitor can see the list of all restaurants.
   resources :restaurants, only: [ :index, :new, :create, :show ] do
    resources :reviews, only: [ :new, :create ]

  end

end
  # end

  # get "restaurants" , to: "restaurants#index"

  # # He can add a new restaurant, and be redirected to the show view of that new restaurant.
  # get "restaurants/new", to: "restaurants#new"
  # post "restaurants", to: "restaurants#create"

  # get "restaurants/:id", to: "restaurants#show", as: :restaurant
  # # He can see the details of a restaurant, with all the reviews related to the restaurant.
  # # get "restaurants/:restaurant_id/reviews",  to: "reviews#index"
  # # GET "restaurants/38"

  # # He can add a new review to a restaurant
  # get "restaurants/:restaurant_id/reviews/new", to: "review#new"
  # post "restaurants/:id/reviews", to: "review#create"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = [
  "chinese",
  "italian",
  "japanese",
  "french",
  "belgian"
 ]
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  validates :rating, numericality: { only_integer: true }
  validates :content, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ActionController::Base

  def index
    @restaurants = Restaurant.all
    # raise
  end

  def new
    @restaurant = Restaurant.new
  end

   def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  # def update
  #   if @restaurant.update(restaurant_params)
  #     redirect_to restaurant_path(@restaurant)
  #   else
  #     render :edit
  #   end
  # end

  def show
     @restaurant = Restaurant.find(params[:id])
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ActionController::Base


  # def index
  #   @reviews = Review.all
  # end
  def new
      # we need @restaurant in our `simple_form_for`
      @restaurant = Restaurant.find(params[:restaurant_id])
      @review = Review.new
    end

    def create
      @review = Review.new(review_params)
      # we need `restaurant_id` to asssociate review with corresponding restaurant
      @review.restaurant = Restaurant.find(params[:restaurant_id])
      if @review.save
        redirect_to restaurant_path(params[:restaurant_id])
      else
        render :new
      end
    end

    private

    def review_params
      params.require(:review).permit(:content, :rating)
    end

end

 # t.text "content"
 #    t.integer "rating"
 #    t.integer "restaurant_id"
 #    t.datetime "created_at", null: false
 #    t.datetime "updated_at", null: false
 #    t.index ["restaurant_id"], name: "index_reviews_on_restaurant_id"

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>My list of restaurants</h1>
<% @restaurants.each do |restaurant| %>
  <h2><%= restaurant.name %></h2>
  <p><%= restaurant.category %></p>
<% end %>

<%= link_to "Create a new restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<!-- <div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3"> -->

      <h1> Please, fill inputs next</h1>
      <%= simple_form_for @restaurant do |f| %>

            <% if @restaurant.errors.any? %>
              <!-- <div class="errors-container"> -->
              <ul>
                <% @restaurant.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                  <% end %>
              </ul>
              <!-- </div> -->
              <% end %>
        <%= f.input :name %>
        <%= f.input :category, collection: Restaurant::CATEGORIES %>
        <%= f.input :address %>
        <%= f.input :phone_number , input_html: {placeholder: "As you want"}%>
        <%= f.button :submit, class: "btn btn-primary" %>
      <% end %>
<%= link_to "Back", restaurants_path %>
 <!--    </div>
  </div>
</div> -->

<!--
{
    name:         'Café des Arts',
    address:      '138 Cours Victor Hugo, 33000 Bordeaux',
    phone_number: '05 56 91 78 46',
    category:     'french'
  }, -->

app/views/restaurants/show.html.erb
<h1>Your restaurant</h1>
<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.category %></p>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>

<%= link_to "Back", restaurants_path %>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant,@review] do |f| %>

            <% if @review.errors.any? %>
              <!-- <div class="errors-container"> -->
              <ul>
                <% @review.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                  <% end %>
              </ul>
              <!-- </div> -->
              <% end %>
        <%= f.input :content %>
        <%= f.input :rating, inclusion:{in: [0, 1, 2, 3, 4, 5]}%>
        <%= f.button :submit, class: "btn btn-primary" %>
      <% end %>

<%= link_to "Back to restaurant list", restaurants_path %>
<!-- t.text "content"
    t.integer "rating"
    t.integer "restaurant_id" -->
<!-- validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] } -->

<!-- # app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %> -->